---
permalink: a250/maintain-overview.html
sidebar: sidebar
keywords: aff A250 maintenance, maintenance, repairing A250, repairing aff A250, replace aff A250 components, replace aff A250 components
summary: Maintain the ASA A250 hardware
---
= Maintain AFF A250 hardware
:icons: font
:imagesdir: ../media/

[.lead]
For the AFF A250 storage system, you can perform maintenance procedures on the following components.

== Boot media

The boot media stores a primary and secondary set of boot image files that the system uses when it boots. 

== Chassis
The chassis is the physical enclosure housing all the controller components such as the controller/CPU unit, power supply, and I/O.

== Controller

A controller consists of a board, firmware, and software. It controls the drives and implements the ONTAP functions.

== DIMM

You must replace a DIMM (dual in-line memory module) when a memory mismatch is present, or you have a failed DIMM.

== Drive

A drive is a device that provides the physical storage media for data.

== Fan
The fan cools the controller.

== Mezzanine card
A Mezzanine card is a printed circuit board that plugs directly into another plug-in card. 

== NVEM battery

A battery is included with the controller and preserves cached data if the AC power fails.

== Power supply

A power supply provides a redundant power source in a controller shelf.

== Real-time clock battery
A real time clock battery preserves system date and time information if the power is off. 
