---
permalink: fas2800/chassis-replace-complete-system-restore-rma.html
sidebar: sidebar
keywords: fas2800, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap
summary: "You must verify the HA state of the chassis and run System-Level diagnostics, switch back aggregates, and return the failed part to NetApp, as described in the RMA instructions shipped with the kit."
---
= Restore and verify the configuration - FAS2800
:icons: font
:imagesdir: ../media/

Verify the HA state of the chassis and run diagnostics, switch back aggregates, and return the failed part to NetApp, as described in the RMA instructions shipped with the kit.

== Step 1: Verify and set the HA state of the chassis

You must verify the HA state of the chassis, and, if necessary, update the state to match your system configuration.

. In Maintenance mode, from either controller module, display the HA state of the local controller module and chassis: `ha-config show`
+
The HA state should be the same for all components.

. If the displayed system state for the chassis does not match your system configuration:
 .. Set the HA state for the chassis: `ha-config modify chassis _HA-state_`
+
The value for HA-state can be one of the following:

*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mccip`
*** `non-ha`

 .. Confirm that the setting has changed: `ha-config show`
. If you have not already done so, recable the rest of your system.
. Exit Maintenance mode: `halt`    The LOADER prompt appears.
. Boot the controller module.

== Step 2: Restore automatic giveback and AutSupport

Restore automatic giveback and AutoSupport if they have been disabled.

. Restore automatic giveback by using the `storage failover modify -node local -auto-giveback true` command.
. Restore Autosupport using the `system node autosupport invoke -node * -type all -message MAINT=END`

== Step 4: Return the failed part to NetApp

include::../_include/complete_rma.adoc[]
