---
permalink: fas2800/dimm-replace.html
sidebar: sidebar
keywords: fas2800, replace, dimm, shut, down, impaired, controller, controller, metrocluster, replace, system, reinstall, diagnostics, module, filed, part, aggregates,
summary: "You must replace a DIMM in the controller module when your system registers an increasing number of correctable error correction codes (ECC); failure to do so causes a system panic."
---
= Replace a DIMM - FAS2800
:icons: font
:imagesdir: ../media/

[.lead]
You must replace a DIMM in the controller module when your system registers an increasing number of correctable error correction codes (ECC); failure to do so causes a system panic.

All other components in the system must be functioning properly; if not, you must contact technical support.

You must replace the failed component with a replacement FRU component you received from your provider.

== Step 1: Shut down the impaired controller

[.lead]
include::../_include/shutdown_most_frus.adoc[]

== Step 2: Remove controller module

[.lead]
To access components inside the controller, you must first remove the controller module from the system and then remove the controller module cover.

.Steps
. If you are not already grounded, properly ground yourself.
. Loosen the hook and loop strap binding the cables to the cable management device, and then unplug the system cables and SFPs (if needed) from the controller module, keeping track of where the cables were connected.
+
Leave the cables in the cable management device so that when you reinstall the cable management device, the cables are organized.

. Remove and set aside the cable management devices from the left and right sides of the controller module.
. Squeeze the latch on the cam handle until it releases, open the cam handle fully to release the controller module from the midplane, and then, using two hands, pull the controller module out of the chassis.
+
image::../media/drw_2240_x_opening_cam_latch.svg[width=340px]

. Turn the controller module over and place it on a flat, stable surface.
. Open the cover by pressing the blue buttons on the sides of the controller module to release the cover, and then rotate the cover up and off of the controller module.
+
image::../media/drw_2850_open_controller_module_cover_IEOPS-695.svg[width=340px]

== Step 3: Replace the DIMMs

[.lead]
To replace the DIMMs, locate them inside the controller and follow the specific sequence of steps.

If you are replacing a DIMM, you need to remove it after you have unplugged the NVMEM battery from the controller module.

.Steps
. If you are not already grounded, properly ground yourself.
+
You must perform a clean system shutdown before replacing system components to avoid losing unwritten data in the nonvolatile memory (NVMEM). The LED is located on the back of the controller module. Look for the following icon:
+
image::../media/drw_hw_nvram_icon.svg[width=70px]

. If the NVMEM LED is not flashing, there is no content in the NVMEM; you can skip the following steps and proceed to the next task in this procedure.
. If the NVMEM LED is flashing, there is data in the NVMEM and you must disconnect the battery to clear the memory:
 .. Locate the battery cable, press the clip on the battery plug to release the lock clip from the plug socket, and then unplug the battery cable from the socket.
 .. Confirm that the NVMEM LED is no longer lit.
 .. Reconnect the battery connector and recheck the LED on the back of the controller.
. Locate the DIMMs on your controller module.
+
. Note the orientation of the DIMM in the socket so that you can insert the replacement DIMM in the proper orientation.
. Eject the DIMM from its slot by gently pulling the locking tabs on the side of the DIMM outward.
+
The DIMM socket will rotate up a little.
. Rotate the DIMM socket as far as it will go, and then slide the DIMM out of the socket. 
+
NOTE: Carefully hold the DIMM by the edges to avoid pressure on the components on the DIMM circuit board.
+
The following illustration shows the location of system DIMMs:
+
image::../media/drw_2850_replace_dimms_IEOPS-699.svg[width=340]

. Remove the replacement DIMM from the antistatic shipping bag, hold the DIMM by the corners, and align it to the slot.
+
The notch among the pins on the DIMM should line up with the tab in the socket.

. Make sure that the DIMM ejector tabs on the connector are in the open position, and then insert the DIMM squarely into the slot.
+
The DIMM fits tightly in the slot, but should go in easily. If not, realign the DIMM with the slot and reinsert it.
+
NOTE: Visually inspect the DIMM to verify that it is evenly aligned and fully inserted into the slot.

. Push carefully, but firmly, on the top edge of the DIMM until the ejector tabs snap into place over the notches at the ends of the DIMM.
. ******Locate the NVMEM battery plug socket, and then squeeze the clip on the face of the battery cable plug to insert it into the socket.
+
*******Make sure that the plug locks down onto the controller module.

. Reinstall the controller module cover.

== Step 4: Reinstall the controller module

[.lead]
After you replace components in the controller module, reinstall it into the chassis.

.Steps
. If you are not already grounded, properly ground yourself.
. If you have not already done so, replace the cover on the controller module.
. Turn the controller module over and align the end with the opening in the chassis.
. Gently push the controller module halfway into the system.Align the end of the controller module with the opening in the chassis, and then gently push the controller module halfway into the system.
+
NOTE: Do not completely insert the controller module in the chassis until instructed to do so.

. Recable the system, as needed.
+
If you removed the media converters (QSFPs or SFPs), remember to reinstall them if you are using fiber optic cables.

. Complete the reinstallation of the controller module:
 .. With the cam handle in the open position, firmly push the controller module in until it meets the midplane and is fully seated, and then close the cam handle to the locked position.
+
NOTE: Do not use excessive force when sliding the controller module into the chassis to avoid damaging the connectors.
+
The controller begins to boot as soon as it is seated in the chassis.

 .. If you have not already done so, reinstall the cable management device.
 .. Bind the cables to the cable management device with the hook and loop strap.
 .. When you see the message `Press Ctrl-C for Boot Menu`, press `Ctrl-C` to interrupt the boot process.
+
NOTE: If you miss the prompt and the controller module boots to ONTAP, enter `halt`, and then at the LOADER prompt enter `boot_ontap`, press `Ctrl-C` when prompted, and then boot to Maintenance mode.

 .. Select the option to boot to Maintenance mode from the displayed menu.

== Step 5: Run system-level diagnostics

[.lead]
After installing a new DIMM, you should run diagnostics.

Your system must be at the LOADER prompt to start System Level Diagnostics.

All commands in the diagnostic procedures are issued from the controller where the component is being replaced.

.Steps
. If the controller to be serviced is not at the LOADER prompt, perform the following steps:
 .. Select the Maintenance mode option from the displayed menu.
 .. After the controller boots to Maintenance mode, halt the controller: `halt`
+
After you issue the command, you should wait until the system stops at the LOADER prompt.
+
NOTE: During the boot process, you can safely respond `y` to prompts:

  *** A prompt warning that when entering Maintenance mode in an HA configuration, you must ensure that the healthy controller remains down.
. At the LOADER prompt, access the special drivers specifically designed for system-level diagnostics to function properly: `boot_diags`
+
During the boot process, you can safely respond `y` to the prompts until the Maintenance mode prompt (*>) appears.

. Run diagnostics on the system memory: `sldiag device run -dev mem`
. Verify that no hardware problems resulted from the replacement of the DIMMs: `sldiag device status -dev mem -long -state failed`
+
System-level diagnostics returns you to the prompt if there are no test failures, or lists the full status of failures resulting from testing the component.

. Proceed based on the result of the preceding step:
+
[options="header" cols="1,2"]
|===
| If the system-level diagnostics tests...| Then...
a|
Were completed without any failures
a|

 .. Clear the status logs: `sldiag device clearstatus`
 .. Verify that the log was cleared: `sldiag device status`
+
The following default response is displayed:
+
SLDIAG: No log messages are present.

 .. Exit Maintenance mode: `halt`
+
The controller displays the LOADER prompt.

 .. Boot the controller from the LOADER prompt: `bye`
 .. Return the controller to normal operation:

|===
+
[options="header" cols="1,2"]
|===
| If your controller is in...| Then...
a|
An HA pair
a|
Perform a give back: `storage failover giveback -ofnode _replacement_node_name_`

NOTE: If you disabled automatic giveback, re-enable it with the storage failover modify command.

a|
A two-node MetroCluster configuration
a|
Proceed to the next step.

The MetroCluster switchback procedure is done in the next task in the replacement process.
a|
A stand-alone configuration
a|
Proceed to the next step.

No action is required.

You have completed system-level diagnostics.

a|
Resulted in some test failures
a|
Determine the cause of the problem:

 .. Exit Maintenance mode: `halt`
+
After you issue the command, wait until the system stops at the LOADER prompt.

 .. Turn off or leave on the power supplies, depending on how many controller modules are in the chassis:
  *** If you have two controller modules in the chassis, leave the power supplies turned on to provide power to the other controller module.
  *** If you have one controller module in the chassis, turn off the power supplies and unplug them from the power sources.
 .. Verify that you have observed all the considerations identified for running system-level diagnostics, that cables are securely connected, and that hardware components are properly installed in the storage system.
 .. Boot the controller module you are servicing, interrupting the boot by pressing `Ctrl-C` when prompted to get to the Boot menu:
  *** If you have two controller modules in the chassis, fully seat the controller module you are servicing in the chassis.
+
The controller module boots up when fully seated.

  *** If you have one controller module in the chassis, connect the power supplies, and then turn them on.
 .. Select Boot to maintenance mode from the menu.
 .. Exit Maintenance mode by entering the following command: `halt`
+
After you issue the command, wait until the system stops at the LOADER prompt.

 .. Rerun the system-level diagnostic test.

|===

== Step 6: Restore automatic giveback and AutSupport

[.lead]
After completing diagnostics and rebooting the node, you need to restore automatic giveback and AutoSupport if they have been disabled.

. Restore automatic giveback by using the `storage failover modify -node local -auto-giveback true` command.
. Restore Autosupport using the `system node autosupport invoke -node * -type all -message MAINT=END`

== Step 7: Return the failed part to NetApp

[.lead]
include::../_include/complete_rma.adoc[]
