---
permalink: fas9000/controller-replace-system-config-restore-and-verify.html
sidebar: sidebar
keywords: aff a700, fas9000, verify, ha, state, controller, module, system, diagnostics
summary: "After completing the hardware replacement and booting to Maintenance mode, you verify the low-level system configuration of the replacement controller and reconfigure system settings as necessary."
---
= Restore and verify the system configuration - AFF A700 and FAS9000
:icons: font
:imagesdir: ../media/

[.lead]
After completing the hardware replacement and booting to Maintenance mode, you verify the low-level system configuration of the replacement controller and reconfigure system settings as necessary.

== Step 1: Set and verify system time after replacing the controller

include::../_include/set_time_after_controller_rep.adoc[]


== Step 2: Verify and set the HA state of the controller module

You must verify the `HA` state of the controller module and, if necessary, update the state to match your system configuration.

.Steps
. In Maintenance mode from the new controller module, verify that all components display the same `HA` state: `ha-config show`
+
The value for HA-state can be one of the following:

*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mccip`
*** `non-ha`

 .. Confirm that the setting has changed: `ha-config show`

