---
permalink: fas8300/maintain-overview.html
sidebar: sidebar
keywords: fas8300 maintenance, maintenance, repairing, repairing fas8300, replace fas8300 components, replace fas8300 components
summary: Maintain the FAS8330 and FAS8700 hardware
---
= Maintain FAS8300 and FAS8700 hardware
:icons: font
:imagesdir: ../media/

[.lead]
For the FAS8300 and FAS8700 storage systems, you can perform maintenance procedures on the following components.

== Boot media

The boot media stores a primary and secondary set of boot image files that the system uses when it boots. 

== Caching module

You must replace the controller’s caching module when your system registers a single AutoSupport (ASUP) message that the module has gone offline.

== Chassis

The chassis is the physical enclosure housing all the controller components such as the controller/CPU unit, power supply, and I/O.

== Controller

A controller consists of a board, firmware, and software. It controls the drives and implements the ONTAP functions.

== DIMM

You must replace a DIMM (dual in-line memory module) when a memory mismatch is present, or you have a failed DIMM.

== Fan

The fan cools the controller.

== NVDIMM battery

A NVDIMM battery is responsible for maintaining power to the NVDIMM module.

== NVDIMM

 The NVDIMM (non-volatile dual in-line memory module) manages the data transfer from the volatile memory to the non-volatile storage, and maintains data integrity in the event of a power loss or system shutdown. 

== PCIe or Mezzanine card

A PCIe (peripheral component interconnect express) card is an expansion card that plugs into the PCIe slot on the motherboard. 

A Mezzanine card is an expansion card that is designed to be inserted into a specialized slot on the motherboard. 

== Power supply

A power supply provides a redundant power source in a controller shelf.

== Real-time clock battery

A real time clock battery preserves system date and time information if the power is off. 